# Generated by Django 4.0.9 on 2023-04-24 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workouts',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='workout_thumbnails/'),
        ),
    ]
