# Generated by Django 4.0.9 on 2023-04-20 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intakeform',
            name='preferred_workout_category',
            field=models.CharField(choices=[('CARDIO', 'Cardio'), ('STRENGTH', 'Strength'), ('FLEXIBILITY', 'Flexibility'), ('BALANCE', 'Balance')], default='Cardio', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intakeform',
            name='preferred_workout_level',
            field=models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='Beginner', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workouts',
            name='calories',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workouts',
            name='category',
            field=models.CharField(choices=[('CARDIO', 'Cardio'), ('STRENGTH', 'Strength'), ('FLEXIBILITY', 'Flexibility'), ('BALANCE', 'Balance')], default='Cardio', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workouts',
            name='level',
            field=models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='Beginner', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workouts',
            name='video_file',
            field=models.FileField(default='', upload_to='workout_videos/'),
            preserve_default=False,
        ),
    ]
