# Generated by Django 4.0.9 on 2023-04-23 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('email_address', models.EmailField(max_length=254)),
                ('current_address', models.CharField(max_length=255)),
                ('education', models.CharField(max_length=255)),
                ('certifications', models.CharField(blank=True, max_length=255, null=True)),
                ('experience_years', models.PositiveIntegerField(blank=True, null=True)),
                ('previous_work_experience', models.TextField(blank=True, null=True)),
                ('fitness_specialization', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientmetrics',
            name='calories_burnt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientmetrics',
            name='completed_workouts',
            field=models.ManyToManyField(blank=True, null=True, related_name='completed_workout', to='core.workoutsassigned'),
        ),
        migrations.AlterField(
            model_name='clientmetrics',
            name='goal_progress',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientmetrics',
            name='meals',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientmetrics',
            name='progress_metrics',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientmetrics',
            name='sleep_cycle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientmetrics',
            name='workouts',
            field=models.ManyToManyField(blank=True, null=True, related_name='assigned_workouts', to='core.workoutsassigned'),
        ),
        migrations.AlterField(
            model_name='intakeform',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='intakeform',
            name='home_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='intakeform',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='intakeform',
            name='preferred_workout_category',
            field=models.CharField(blank=True, choices=[('CARDIO', 'Cardio'), ('STRENGTH', 'Strength'), ('FLEXIBILITY', 'Flexibility'), ('BALANCE', 'Balance')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='intakeform',
            name='preferred_workout_level',
            field=models.CharField(blank=True, choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='intakeform',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workouts',
            name='category',
            field=models.CharField(blank=True, choices=[('CARDIO', 'Cardio'), ('STRENGTH', 'Strength'), ('FLEXIBILITY', 'Flexibility'), ('BALANCE', 'Balance')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workouts',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='workouts',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workouts',
            name='level',
            field=models.CharField(blank=True, choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workouts',
            name='rating',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='workouts',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='workout_videos/'),
        ),
        migrations.AlterField(
            model_name='workouts',
            name='views',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='workoutsassigned',
            name='completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='workoutsassigned',
            name='date_assigned',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workoutsassigned',
            name='date_completed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workoutsassigned',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workoutsassigned',
            name='workout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.workouts'),
        ),
    ]
