# Generated by Django 4.0.9 on 2023-04-21 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_intakeform_preferred_workout_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkoutVideo',
        ),
        migrations.AddField(
            model_name='workouts',
            name='duration',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
