# Generated by Django 4.0.9 on 2023-04-06 03:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntakeForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('body_fat_percentage', models.FloatField()),
                ('resting_heart_rate', models.IntegerField()),
                ('blood_pressure', models.CharField(max_length=20)),
                ('medications', models.TextField(blank=True)),
                ('medical_conditions', models.TextField(blank=True)),
                ('exercise_frequency', models.CharField(max_length=255)),
                ('exercise_intensity', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
