# Config for Dependabot updates. See Documentation here:
# https://docs.github.com/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates

version: 2
updates:
  # Update GitHub actions in workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "update"
    # Disable all pull requests for github-actions
    open-pull-requests-limit: 0
  # Enable version updates for Docker
  # We need to specify each Dockerfile in a separate entry because Dependabot doesn't
  # support wildcards or recursively checking subdirectories. Check this issue for updates:
  # https://github.com/dependabot/dependabot-core/issues/2178
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `compose/local/django` directory
    directory: "/"
    # Check for updates to GitHub Actions every weekday
    schedule:
      interval: "weekly"
    # Disable all pull requests for Docker dependencies
    # https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#open-pull-requests-limit
    open-pull-requests-limit: 0

  # Enable version updates for Python/Pip - Production
  - package-ecosystem: "pip"
    # Look for a `requirements.txt` in the `root` directory
    # also 'setup.cfg', 'runtime.txt' and 'requirements/*.txt'
    directory: "base/requirements/*.txt"
    # Check for updates to GitHub Actions every weekday
    schedule:
      interval: "weekly"
    # Disable all pull requests for pip dependencies
    open-pull-requests-limit: 0
