# note: might need testing...
version: "3"

volumes:
  production_postgres_data: { }
  production_postgres_data_backups: { }
  production_traefik: { }

services:
  app:
    build:
      context: .
      args:
        - DEV=false
        - BUILD_ENVIRONMENT=prod
    container_name: wrike_prod_django
    ports:
      - "8000:8000"
    volumes:
      - ./base:/base
    command: compose/prod-env/django/entrypoint.sh
    env_file:
      - ./base/.envs/.production/.django
      - ./base/.envs/.production/.postgres
      - ./base/.envs/.production/.wrike
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    container_name: wrike_prod_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./base/.envs/.production/.postgres

  traefik:
    build:
      context: .
      dockerfile: compose/prod-env/traefik/Dockerfile
    container_name: wrike_prod_traefik
    depends_on:
      - app
    volumes:
      - production_traefik:/etc/traefik/acme
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
